<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPAvmIbx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPAvmIbx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPAvmIbx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPAvmIbx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPAvmIbx\App_KernelDevDebugContainer([
    'container.build_hash' => 'PAvmIbx',
    'container.build_id' => '37108855',
    'container.build_time' => 1722424710,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPAvmIbx');
